name: gogo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.17

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/drawable/
    - assets/typo/

  uses-material-design: true

  fonts:
    - family: sans
      fonts:
        - asset: assets/typo/GmarketSansBold.otf
        - asset: assets/typo/GmarketSansLight.otf
        - asset: assets/typo/GmarketSansMedium.otf