name: gogo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  dio: ^5.1.0
  get_it: ^7.6.4
  retrofit: ^4.0.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.0.6
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/drawable/
    - assets/typo/

  uses-material-design: true

  fonts:
    - family: suit
      fonts:
        - asset: assets/typo/SUIT-ExtraBold.otf
          weight: 800
        - asset: assets/typo/SUIT-SemiBold.otf
          weight: 600
